### ISSUE TITLE
Pinned tabs revert order when switching to an other window

### ISSUE THREAD

**Issue by fthommen** [BlackGlory/active-pinned-tab#2]
First of all: This is a truly great plugin!  The times are gone when I had to search for my pinned tabs in the other browser window on the other screen and therefore was forced to switch browser windows back and forth :-)

However when switching windows, the order or the pinned tabs is inverted each time.  This doesn't put the usefulness of the plugin into question, but when you are used to semi-blindly klick in the spot where you expect the tab to be, then you are wrong after each window switch.

**Comment by grahamperrin** [comment]
Active Pinned Tab `1.0.0`, Tree Style Tab `3.7.2` and other extensions added to release candidate 3 of Firefox `86.0` on FreeBSD `14.0-CURRENT`. 

With my everyday _default_ profile, where I hide the tab bar of Firefox:

* initially, the issue was not reproducible

– the order of pins at the head of the sidebar of Tree Style Tab remained consistent through multiple tests. 

With my _test_ profile in a second instance of Firefox and the tab bar of Firefox visible: 

* initially, not reproducible. 

Through repeatedly switching from one instance of Firefox to another, I began to reproduce the issue. 

As far as I can tell, the issue is more likely to occur if there's a switch away from Firefox. 

@fthommen please, can you tell more about the environment in which you run Firefox?

**Comment by fthommen** [comment]
Firefox 86 (was an earlier version when I wrote the issue, but the behaviour has not changed) on macOS 11.2.2 (Big Sur). For me the effect shows up almost immediately: Open a new Firefox Window -> Tabs are in the same order as in original Window -> Switch back to first Window -> Tabs are in inverted order.

I have Active Pinned Tab `1.0.0` and quite some other add-ons.

**Comment by fthommen** [comment]
I have retried with a fresh browser profile and Active Pinned Tab as only add-on.  There are also no disabled add-ons installed.  See the attached screen recording

https://user-images.githubusercontent.com/279232/109397151-91b94d80-7935-11eb-86bb-061e562d41a1.mov

**Comment by grahamperrin** [comment]
Thanks. I shouldn't laugh, but it _is_ slightly comical in its predictability there on macOS! 

I guess that window-walking in KDE Plasma (or should I say KWin?) either does not, or is less likely to, expose the issue _if_ the walking is confined to just one instance of Firefox.
